/* Generated By:JavaCC: Do not edit this line. JSONParserTreeConstants.java Version 7.0.12 */
package org.example.JavaCCParser;

public interface JSONParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJT_OBJECT = 1;
  public int JJTMEMBERS = 2;
  public int JJTPAIR = 3;
  public int JJTFIELDNAME = 4;
  public int JJT_ARRAY = 5;
  public int JJTELEMENTS = 6;
  public int JJTVALUE = 7;


  public String[] jjtNodeName = {
    "parse",
    "_object",
    "members",
    "pair",
    "fieldName",
    "_array",
    "elements",
    "value",
  };
}
/* JavaCC - OriginalChecksum=2bfe31fa2bbad0833c713c1b79812575 (do not edit this line) */
